# Generated by Django 5.0.3 on 2024-04-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
