# Generated by Django 5.0.3 on 2024-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_article_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hobby',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('hobby', 'Hobby'), ('food', 'Food'), ('programming', 'Programming')], default='hobby', max_length=50),
        ),
    ]
