# Generated by Django 5.0.4 on 2024-04-04 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
