# Generated by Django 5.0.3 on 2024-04-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Article',
        ),
    ]
